### ISSUE TITLE
lein new reagent foo doesn't work

### ISSUE THREAD

**Issue by borkdude** [reagent-project/reagent-template#1]
Borkdude@fina000 /tmp $ lein new reagent foo
Failed to resolve version for reagent:lein-template:jar:RELEASE: Could not find metadata reagent:lein-template/maven-metadata.xml in local (/Users/Borkdude/.m2/repository)
This could be due to a typo in :dependencies or network issues.
If you are behind a proxy, try setting the 'http_proxy' environment variable.
Could not find template reagent on the classpath.

**Comment by whatacold** [comment]
Hi,

I also ran into this today when I was trying to play with reagent, but failed (lein version `2.9.6`):

```
$ lein new reagent-frontend play-reagent-frontent
Failed to resolve version for reagent-frontend:lein-template:jar:RELEASE: Could not find metadata reagent-frontend:lein-template/maven-metadata.xml in local (/home/whatacold/.m2/repository)
Failed to read artifact descriptor for reagent-frontend:lein-template:jar:RELEASE
This could be due to a typo in :dependencies, file system permissions, or network issues.
If you are behind a proxy, try setting the 'http_proxy' environment variable.
Could not find template reagent-frontend on the classpath.
```

But `lein new reagent foo` works, what could be the problem?

**Comment by yogthos** [comment]
Hi,

I'm not able to reproduce the issue locally. One thing to try might be to clear out `~/.m2/repository/reagent-frontend/lein-template` folder to see if there's a cached template causing an issue.

**Comment by whatacold** [comment]
Thanks.

After `mv ~/.m2/repository/reagent-frontend/{,.bak}`, it still doesn't work, and the error message is same.

But I notice that a new `~/.m2/repository/reagent-frontend/` is created:
```
# pwd is ~/.m2/repository
$ tree reagent-frontend/
reagent-frontend/
└── lein-template
    └── resolver-status.properties

$ cat reagent-frontend/lein-template/resolver-status.properties
#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Tue Aug 31 00:36:44 CST 2021
maven-metadata-tsinghua.xml/@192.168.1.1\:12345>@default-tsinghua-https\://mirrors.tuna.tsinghua.edu.cn/clojars/.lastUpdated=1630341404261
maven-metadata-aliyun.xml.error=Could not transfer metadata reagent-frontend\:lein-template/maven-metadata.xml from/to aliyun (https\://maven.aliyun.com/repository/public/)\: Checksum validation failed, no checksums available
maven-metadata-aliyun.xml/@192.168.1.1\:12345>@default-aliyun-https\://maven.aliyun.com/repository/public/.lastUpdated=1630341404488
maven-metadata-tsinghua.xml.error=Could not transfer metadata reagent-frontend\:lein-template/maven-metadata.xml from/to tsinghua (https\://mirrors.tuna.tsinghua.edu.cn/clojars/)\: Checksum validation failed, expected f5a8f4da358ee257ead04c314c047dedefbe2962 but is 87caff4a2f9beaad6c80c4f015ac1db0435d27b3
```

In the properties file, 192.168.1.1:12345 is a http proxy, and tsinghua & aliyun are mirrors that I use.

Looks like a mirror problem?

**Comment by yogthos** [comment]
Yeah that sounds plausible.

**Comment by whatacold** [comment]
Just confirmed that the problem is caused by the mirrors. After removing mirrors from `~/.lein/profiles.clj`, `lein new reagent-frontend myproject` works.

FYI, now `~/.m2/repository/reagent-frontend/lein-template/resolver-status.properties` is as follows:
```
#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Sun Sep 05 10:28:09 CST 2021
maven-metadata-clojars.xml.lastUpdated=1630808889985
maven-metadata-central.xml.lastUpdated=1630808888850
maven-metadata-central.xml.error=
```
