### ISSUE TITLE
Add the dev commands into new project README

### ISSUE THREAD

**Issue by Frozenlock** [reagent-project/reagent-template#100]
I find myself returning to old project without knowing which command was acceptable.
(`lein figwheel` vs `lein figwheel devcards`, how to start a repl, compiling _less_ files...)

I can check `reagent-template`'s  readme, but I'm afraid one day the old projects won't be compatible with some new commands. Then it will be a game of "guess what was the development tool back then".

I think injecting the [development mode](https://github.com/reagent-project/reagent-template#development-mode) section into new `readme` (which is empty anyway) would help to make projects future-proof.

Thoughts?

**Comment by yogthos** [comment]
Yeah, that might not be a bad idea. Would probably also make sense to add a changelog and maybe add something like `:reagent-template-version` key to `project.clj` that's generated. That way you could see what version of the template the project was made with and check the changelog.

**Comment by yogthos** [comment]
Looks great thanks!
