### ISSUE TITLE
[QUESTION]what is `app-dependencies` means

### ISSUE THREAD

**Issue by zjhmale** [reagent-project/reagent-template#101]
in [project.clj template](https://github.com/reagent-project/reagent-template/blob/master/src/leiningen/new/reagent/project.clj#L22), what is `app-dependencies` means, i can not find any usage in this project or the leiningen project.

**Comment by Frozenlock** [comment]
IIRC it's from a previous version of the template; I wanted to allow users to create a "library" project without injecting a number of superfluous dependencies.

See https://github.com/reagent-project/reagent-template/commit/0ebeb35438c771eb4366983839bc7b5dd852d69a#diff-04c6e90faac2675aa89e2176d2eec7d8R21

I think this feature did not survive, so `app-dependencies` and the others like it can probably be removed.
