### ISSUE TITLE
Uncaught ReferenceError: goog is not defined in vanilla project

### ISSUE THREAD

**Issue by BigTom** [reagent-project/reagent-template#11]
I get Uncaught ReferenceError: goog is not defined in javascript console for the vanilla project.  I am assuming this is related to the:

``` javascript
<script type="text/javascript">goog.require("rproj.dev");</script>
```

line in the index.html (where rproj is the <name> in "lein new reagent <name>" )

I am new to this so it may be normal?   But doesn't seem right.

**Comment by engrki** [comment]
I am new on ionic can you elaborate how you solve the issue. I am facing the same. What means by RTFM
