### ISSUE TITLE
resources shouldn't be using relative path: 404 when using/nested/path

### ISSUE THREAD

**Issue by Frozenlock** [reagent-project/reagent-template#110]
Everything works fine if you are on "/" or "/index.html", but it fails if you are on "/a/index.html" because the resources are asked with "http://localhost:3449**/a/**js/app.js"

**Comment by yogthos** [comment]
ah makes sense ;)

**Comment by yogthos** [comment]
ok should be fixed, I'll push a new version out tonight

**Comment by yogthos** [comment]
ok latest is up on clojars, let me know if it looks good

**Comment by Frozenlock** [comment]
Yup!

Amazing speed, as always :smile:

**Comment by yogthos** [comment]
thanks :)
