### ISSUE TITLE
NullPointerException on Windows

### ISSUE THREAD

**Issue by dpetranek** [reagent-project/reagent-template#112]
Trying to start the application on Windows with lein figwheel produces a NullPointerException.

Steps to reproduce (Windows 10 or Windows 7):
1. lein new reagent <project>
2. cd <project>
3. lein figwheel

Produces this stacktrace: https://www.refheap.com/116767

I discovered the issue when I moved a new project I started early this week on a linux box to a Windows 7 computer. I had already done development on that project, so I tried it again with the plain template. I was also able to reproduce it on a Windows 10 computer. It does not appear to be a problem on linux at all.

**Comment by yogthos** [comment]
Hmm, this doesn't seem to trace to anything in the project itself. It might be worth opening an issue with Figwheel, as it seems to be having trouble running its validation on Windows.

**Comment by dpetranek** [comment]
Whoops, you're right: https://github.com/bhauman/lein-figwheel/issues/364
I think we can close this then, I'll follow up there.

**Comment by yogthos** [comment]
by the way, [looks like bumping up figwheel may address the issue](https://github.com/reagent-project/reagent-frontend-template/pull/4), I've just pushed an update out

**Comment by dpetranek** [comment]
Thanks, can confirm everything works as expected with the updated template/figwheel version.
