### ISSUE TITLE
CSS does not work with devcards

### ISSUE THREAD

**Issue by edipofederle** [reagent-project/reagent-template#116]
Hi guys,

I need some extra configuration in order to make CSS works with devcards.

I just created a new project using `reagent-template` with support for devcards and everything works well, except that the CSS seem not be included when I tried using devcards. If a access http://localhost:3449/ everything is fine.

Some support here? Or I missed something.

Thanks in advance

**Comment by yogthos** [comment]
Ah, yeah looks like an omission [here](https://github.com/reagent-project/reagent-template/blob/master/resources/leiningen/new/reagent/src/clj/reagent/handler.clj#L21). The css is only included on the main page.

**Comment by edipofederle** [comment]
Hi @yogthos  This omission is deliberate or she should not be there?

**Comment by yogthos** [comment]
That was an omission on my part, just pushed a new version out with a fix

**Comment by edipofederle** [comment]
Nice. Thank you.
