### ISSUE TITLE
Document how to use Clojure auto-reloading

### ISSUE THREAD

**Issue by drpepper** [reagent-project/reagent-template#118]
Newbie problem: It's obvious how auto-reload for ClojureScript works via Figwheel because the template tells you to run it. But I can't figure out how to get the Clojure code to reload automatically, though I see `ring.middleware.reload` referenced in the project. 

It's probably obvious to Clojure users, but not to me!

**Comment by yogthos** [comment]
The Clojure code should reload when the app is run using `lein run`, the reload middleware watches for changes in the namespaces and tries to recompile them as needed.

**Comment by drpepper** [comment]
Ok, got it! In fact it was working just fine, but because nothing was written to the console I hadn't realized. Thanks for the help.

**Comment by yogthos** [comment]
no prob :)
