### ISSUE TITLE
Broken devcards

### ISSUE THREAD

**Issue by t3chnoboy** [reagent-project/reagent-template#120]
Project with `+devcards` option doesn't work.
I'm getting the following error message in browser console: `Uncaught Error: js/ReactDOM is missing`

**Comment by yogthos** [comment]
Yeah looks like devcards is not compatible with the latest Reagent since it moved to use React 0.15 API. The version of  devcards included in the template is a bit out of date. I'll test with the latest devcards and let you know how that goes.

**Comment by t3chnoboy** [comment]
@yogthos I've opened a PR https://github.com/reagent-project/reagent-template/pull/121

**Comment by yogthos** [comment]
Thanks, I just ended up bumping up devcards as well, I ended up using figwheel 0.5.3-2 though, because 0.5.4 doesn't appear to load the Js consistently for me. Let me know if latest on Clojars looks to be working right.

**Comment by t3chnoboy** [comment]
Cool, thanks! 
I'm having the same issues with `figwheel 0.5.4` 😞 
I saw you've opened an issue https://github.com/bhauman/lein-figwheel/issues/428
But new error reporting is too good not to use 😊

**Comment by yogthos** [comment]
yeah I'm really looking forward to having that going as well :)
