### ISSUE TITLE
Passing route params to reagent app

### ISSUE THREAD

**Issue by achernyak** [reagent-project/reagent-template#126]
Would it be possible to provide an example in the readme of passing route params to the Reagent router?

Base route works fine and you are able to navigate to Reagent links from there. However, if you try to navigate directly to a route provided by Reagent, you get a `Not found` page.

I am fairly new to Ring, so this might be just my lack of knowledge on how to handle this.

**Comment by yogthos** [comment]
You would need to define the routes on the server or have a catchall `*` route. You can see an example [here](https://github.com/yogthos/memory-hole/blob/master/src/clj/memory_hole/routes/home.clj) where the server side routes are defined to match the ones defined on the client [here](https://github.com/yogthos/memory-hole/blob/master/src/cljs/memory_hole/routes.cljs).

**Comment by achernyak** [comment]
Thanks for the help. That just makes too much sense.

I was expecting a behaviour similar to rails and need to explicitly pass the path to the spa.

**Comment by yogthos** [comment]
👍
