### ISSUE TITLE
No source maps

### ISSUE THREAD

**Issue by Engelberg** [reagent-project/reagent-template#130]
I'm not getting any source maps with this template.  I'm using Firefox and the debugger is set to use source maps if present.  Is there something special I need to do in the project.clj file to activate source maps beyond what is already there?

**Comment by yogthos** [comment]
The `:source-map true` compiler option should be all you need. I just tried a fresh project in Chrome and source maps are working as expected. However, I did not get source maps in Firefox either.

**Comment by Atsman** [comment]
Everything perfectly works on my machine in latest chrome.

**Comment by yogthos** [comment]
I think we can close this one.
