### ISSUE TITLE
Duplicate initialization call?

### ISSUE THREAD

**Issue by hrehfeld** [reagent-project/reagent-template#135]
I'm trying the template, but I need to configure figwheel with a different :websocket-host:

      {:builds {:dev
            {:source-paths ["src/cljs" "src/cljc" "env/dev/cljs"]
             :figwheel {
                        :websocket-host "192.168.1.101"}
     ....

This is NOT working in this template, but works in the getting started example.

The problem seems to be that two init calls are generated. [The first one has hardcoded websocket params](https://github.com/reagent-project/reagent-template/blob/master/resources/leiningen/new/reagent/env/dev/cljs/reagent/dev.cljs#L7):

    (figwheel/watch-and-reload
      :websocket-url "ws://localhost:3449/figwheel-ws"
      :jsload-callback core/mount-root)

I can just comment out these lines, and everything works fine. I think this is a bug, and the call should be removed. The figwheel function even says: ["legacy interface"](https://github.com/bhauman/lein-figwheel/blob/92611acb673c870061dd4afc7dbacbf2521a64f6/support/src/figwheel/client.cljs#L472)

**Comment by yogthos** [comment]
I think you're right, the legacy code never got removed from the tempalte.

**Comment by yogthos** [comment]
fixed by https://github.com/reagent-project/reagent-template/commit/7820f4afb490132694eeed472eba5630c0ddc17c

**Comment by hrehfeld** [comment]
Thanks!
