### ISSUE TITLE
Replace less plugin

### ISSUE THREAD

**Issue by Deraen** [reagent-project/reagent-template#139]
In my very biased opinion [less4clj](https://github.com/Deraen/less4clj) would be better choice than [lein-less](https://github.com/montoux/lein-less).

Pros:
- Uses [native Java less compiler](https://github.com/SomMeri/less4j) instead of very old Less.js (1.7.2 instead of 2.7.3)
    - new Less.js doesn't support Nashorn so updating lein-less is very hard
    - Latest less4j has feature parity with less.js 2.6.0 features
- Uses recent Less version 
- Allows importing files directly from classpath (e.g. webjars and cljsjs packages)

I can implement this if others agree this is good idea.

**Comment by yogthos** [comment]
That sounds reasonable to me, would you be up for doing a pr?
