### ISSUE TITLE
Routing atom should be defined with defonce

### ISSUE THREAD

**Issue by jmlsf** [reagent-project/reagent-template#141]
The routing atom defined at 

https://github.com/reagent-project/reagent-template/blob/c27953b3fd30a816556c6821fbc7076247774848/resources/leiningen/new/reagent/src/cljs/reagent/core.cljs#L20

gets reloaded by figwheel whenever you edit any code.  This results in the default home-page component getting reloaded (and gets the current page out of sync with the current URL).  I think a one-line change to defonce is what's needed.  (It works for me.)

**Comment by yogthos** [comment]
👍

**Comment by yogthos** [comment]
just pushed out an update with the change
