### ISSUE TITLE
Lein run not working

### ISSUE THREAD

**Issue by pyb** [reagent-project/reagent-template#143]
I have tested this with the sample trivial project shipped with the template.

`lein run` does not create the file js/app.js, which means I get the `ClojureScript has not been compiled!` message.

However, `lein uberjar` works as intended.

**Comment by pyb** [comment]
Fixed by running `lein cljsbuild once` before `lein run`

**Comment by yogthos** [comment]
The proper way to compile ClojureScript in development is to run `lein figwheel` in a separate terminal. The  `lein run` command compiles server side code, while Figwheel hotloads changes for the front-end.
