### ISSUE TITLE
a uberjar bug

### ISSUE THREAD

**Issue by L-jasmine** [reagent-project/reagent-template#168]
https://github.com/reagent-project/reagent-template/blob/4a6d44d554cde1f3d4c22ee0b30e3ebc57c8c8a1/resources/leiningen/new/reagent/env/prod/clj/reagent/middleware.clj#L6

I think there may be is
[#(wrap-defaults % site-defaults)]

**Comment by yogthos** [comment]
Ah yes, good catch!
