### ISSUE TITLE
Indicate that the system.properties file is for Heroku

### ISSUE THREAD

**Issue by jhacksworth** [reagent-project/reagent-template#173]
As someone unfamiliar with Heroku, I had no idea what the purpose of the `system.properties` file was. After searching for longer than I care to admit, I found this [stackoverflow thread](https://stackoverflow.com/questions/49287187/is-system-properties-only-a-heroku-thing). 👀 

The reason I'm using this template is that I'm following along with _Web Development with Clojure_, _Appendix 5: Writing RESTful Web Services with Liberator_.

Maybe it would be good to mention in the README? This is just a suggestion, feel free to close this issue immediately after reading. 😄

**Comment by yogthos** [comment]
Oh good idea, I'll add a note in the README. :)
