### ISSUE TITLE
Insufficient Java heap space on Windows

### ISSUE THREAD

**Issue by taoroalin** [reagent-project/reagent-template#179]
The default heap space on windows is insufficient to run `shadow-cljs watch app`. This can be solved by adding `:jvm-opts ["-Xmx1G"]` to project.clj.

**Comment by yogthos** [comment]
Thanks for the solution, updated the template to add the `:jvm-opts` as the default.

**Comment by yogthos** [comment]
Thanks for the solution, updated the template to add the `:jvm-opts` as the default.
