### ISSUE TITLE
License file in generated project

### ISSUE THREAD

**Issue by mtsknn** [reagent-project/reagent-template#182]
I generated a new Reagent project with `lein new reagent myproject`. The generated project has [the template's license file](https://github.com/reagent-project/reagent-template/blob/master/LICENSE).

Can I just remove the license file? I don't want to violate the MIT license, so I don't know if that's OK.

If I have already made a couple of commits, am I allowed to remove the license file afterwards? I.e. the license file would still exist in the first few commits.

If I can't remove the license file, how should I properly state that the project is by me, but the template is by reagent-project (as stated in the license file: "Copyright (c) 2014 reagent-project")?

I'm not asking for legal advice per se, just trying to understand what to do with the license file while respecting the MIT license. 😃

**Comment by yogthos** [comment]
Oh yeah you can definitely remove the license file, it's really there more as a sample than anything else. :)

**Comment by mtsknn** [comment]
All right, thanks. 👍 I modified my initial commit so Reagent's license file doesn't exist in any of my project's commits.

To make this easier for others, would it be possible to modify the template so that the license file wouldn't be included in the generated projects? Licenses and other legal things are scary. 😄

**Comment by yogthos** [comment]
Yup that akes sense, I've update the template to remove the license from the generated template.

**Comment by mtsknn** [comment]
Great, thanks! Looks like you removed it from the front-end template as well. 👍

**Comment by yogthos** [comment]
keeping consistent :)
