### ISSUE TITLE
ClassNotFoundException when running shadow-cljs watch app

### ISSUE THREAD

**Issue by rijkt** [reagent-project/reagent-template#184]
First of all, thank you for your work in this, I already learned a lot by studying the generated project structure.

### Reproduction
`lein new reagent <project-name>`
`cd <project-name>`
`npm install`
`shadow-cljs watch app`
This gives me a ClassnotFoundException for com.google.javascript.jscomp.JSChunk. See [output.log](https://github.com/reagent-project/reagent-template/files/7653782/output.log) for full output.

### My setup
OS: Arch Linux
Clojure version: 1.10.3.1040-1
JDKs tried: 8, 16, 17
npm version: 8.1.3-1
leiningen version: 2.9.8-1

**Comment by yogthos** [comment]
Thanks for the report. Looks like the issue was caused by a dependency incompatibility with latest shadow-cljs. I just pushed out an update that should fix it.

**Comment by rijkt** [comment]
Great, I just tested this again and now it works. Thanks for the quick response!
