### ISSUE TITLE
browser fails to load fresh figwheel created javascript

### ISSUE THREAD

**Issue by yatesco** [reagent-project/reagent-template#19]
When making a change in a cljs file figwheel compiles it, states ```notifying browser that file changed: ...``` but the browser ignores the latest and throws a warning: ```Failed to execute 'write' on 'Document': It isn't possible to write into a document from an asynchronously-loaded external script unless it is explicitly opened.```

Steps to reproduce:
 - ```lein new reagent reagent-test```
 - ```cd reagent-test```
 - ```lein ring server```
 - ```lein repl```
 - (in repl) ```(start-figwheel)```
 - (once figwheel has finished compiling) start a browser
 - edit src/cljs/reagent-test/core.cljs (e.g. add a space) and save
 - wait for figwheel to compile
 - boom

The behaviour is the same regardless of whether the browser-repl is started and attached to the browser.

Tested in latest Chromium and Firefox.

**Comment by escherize** [comment]
:+1: I'm getting this as well.

Tested in Chrome.

**Comment by yogthos** [comment]
Turns out the problem is with the code here:

```clojure
(secretary/defroute "/" []
  (session/put! :current-page home-page))

(secretary/defroute "/about" []
  (session/put! :current-page about-page))
```
The variable referring to the page ends up being bound in a namespace that's not refreshed, so when changes are pushed the stale variable is still in use. using a function gets around the problem.

In the next release of ClojureScript it'll be possible to do the following to get around the problem:

```clojure
(secretary/defroute "/" []
  (session/put! :current-page #'home-page))

(secretary/defroute "/about" []
  (session/put! :current-page #'about-page))
```

Using `(fn [] )` as @escherize  doing is another way to get around that.

**Comment by yogthos** [comment]
updated the template to latest ClojureScript and added the fix for reloading.

**Comment by royki** [comment]
I am getting this now. How to fix it ????

**Comment by yogthos** [comment]
This should work as long as the top level components that are being reloaded are referenced using `#'` or wrapped using `(fn [] )`. I'm not able to reproduce the issue using the latest template.

**Comment by ftravers** [comment]
Also make sure the file that does your defroute has 

^:figwheel-always

in the namespace.
