### ISSUE TITLE
App deployed to Heroku cannot start in 60 seconds

### ISSUE THREAD

**Issue by ilyabo** [reagent-project/reagent-template#25]
I am having difficulties deploying an app built with the template to Heroku. The generated Procfile tries to run the following task in a web worker:

     web: lein with-profile production trampoline ring server

When executing this task Leiningen begins downloading a gazillion of dependencies including the ones unnecessary for production (e.g figwheel), in spite of the fact that the standalone .jar file had already been built by the slug compiler. This results in the following error:

    2014-12-29T00:58:50.506270+00:00 heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
    2014-12-29T00:58:50.506504+00:00 heroku[web.1]: Stopping process with SIGKILL
    2014-12-29T00:58:51.285273+00:00 heroku[web.1]: Process exited with status 137
    2014-12-29T00:58:51.290057+00:00 heroku[web.1]: State changed from starting to crashed
    
I tried changing the Procfile so that the jar file is executed directly: 

    web: java $JVM_OPTS -jar target/myapp.jar 

But this doesn't work either, as the ring handler namespace does not include the -main method, and for some reason, ```lein uberjar``` does not generate a self-executable ring server.

What's the right way to run the app on Heroku and to avoid fetching dependencies in the web worker?

**Comment by ioRekz** [comment]
What's the preferred way to deploy to heroku right now ?
You proposed a Procfile running the uberjar but the template one still use lein trempoline.
Also, the template Procfile is
-web: lein with-profile production trampoline ring server
And I think the leading dash make it be ignored by heroku so it uses its default clojure web proctype

**Comment by yogthos** [comment]
The dash is a typo, but otherwise the lein version should be fine for most cases. The alternative would be to add a main and use `web: java $JVM_OPTS -jar target/myapp.jar ` in the Procfile as described above.

**Comment by ioRekz** [comment]
Ok, I had to use this one to avoid the 60sec timeout

**Comment by yogthos** [comment]
I think I'll just add a main for heroku to avoid the confusion

**Comment by ioRekz** [comment]
Yep, would be useful :p

**Comment by yogthos** [comment]
ok just push out a new version with a `server.clj` that's used as a main when building using `lein uberjar` this will make it easier to add support for http-kit in the future as well since lein-ring doesn't support it either.

**Comment by theronic** [comment]
A previously working build threw an R10 and H10 on a redeploy. Redeploying fixed it - there must be some cache that needs to heat up on Heroku. Worrying that it's not dependable. May also have something to do with queued up requests hitting cold app at once and triggering an alarm that causes an H10 state.
