### ISSUE TITLE
Add testing infrastructure to the generated project

### ISSUE THREAD

**Issue by ducky427** [reagent-project/reagent-template#27]
I think that the generated project.clj should have the testing infrastructure present in it.

**Comment by yogthos** [comment]
would you be up for adding that?

**Comment by ducky427** [comment]
I'll give it a shot. I am planning to use clojurescript.test framework as cljs.test is still too new and doesn't have the supporting tools yet.

**Comment by yogthos** [comment]
That sounds reasonable, I think something that has better tooling would definitely be a good way to go. It might make sense to make this an optional flag though as it relies on having phantom.js installed as I recall?

**Comment by ducky427** [comment]
That's correct. You would need phantomjs installed. So an optional flag makes sense.

**Comment by ducky427** [comment]
I've added a test to a sample repo ducky427/reagtest@73ef6ba2da1c48f3c65e82e5f6a99495c6393265

Notes:
- We needed some polyfills as phantomjs was missing some functions. I copied them over from om-tools.
- We don't have access to react_with_addons.js as its not bundled with reagent. So I just copied over some functions reagent's tests were also using.

Once we are ok with this end result, I can add the changes the template.

**Comment by yogthos** [comment]
That seems reasonable to me, @holmsand, @seancorfield, @Frozenlock, @gadfly361 any comments suggestions before we merge this in? :)

**Comment by Frozenlock** [comment]
All I can say is that it's more than time that I start testing they UI side of my reagent apps. Having it baked in the template would be very nice. :+1:

**Comment by gadfly361** [comment]
Whenever I want to test things, I have been using Chestnut because it includes speclj. So I am excited to see a testing addition to reagent-template! :+1:

**Comment by seancorfield** [comment]
Big :+1: from me for building testing into the template!

**Comment by ducky427** [comment]
Great. I've just sent a P-R for this. Please have a look and let me know what I have done is appropriate.

cheers!

**Comment by yogthos** [comment]
everything looks good to me, I pushed the latest on Clojars

**Comment by ducky427** [comment]
cheers!
