### ISSUE TITLE
Not connecting on ws://localhost:9001

### ISSUE THREAD

**Issue by numinasthmatic** [reagent-project/reagent-template#28]
I generate a brand new project with
$ lein new reagent rt

After 
$ lein cljsbuild once
$ lein ring server
...somewhere else...
$ lein repl
(browser repl)

I cannot connect using ws://localhost:9001

I get, on Chrome,
This webpage is not available
The webpage at ws://localhost:9001/ might be temporarily down or it may have moved permanently to a new web address.
Error code: ERR_DISALLOWED_URL_SCHEME

If I try http://localhost:9001, I get
Please connect with a web socket!
which comes directly from weasel, so there is a server listening.

Any idea what I'm doing wrong.

OS X 10.10.1 (Yosemite.)

**Comment by yogthos** [comment]
The template is setup to use figwheel to handle code reloading. Instead of running `lein cljsbuild once` try running `lein figwheel`

**Comment by numinasthmatic** [comment]
Never mind.  Grade 1 user error.

**Comment by CTimmerman** [comment]
I guess it's a server issue. What fixed it?
