### ISSUE TITLE
hook-browser-navigation! not reloadable?

### ISSUE THREAD

**Issue by numinasthmatic** [reagent-project/reagent-template#32]
This comment precedes the definition of hook-browser-navigation!
;; History
;; must be called after routes have been defined

I thought this might cause a problem with fig wheel if routes were added to the code.  This *seems* to be the case.  Can anyone else confirm this?  If so, is there a way to define this so that it will work when routes are added?

**Comment by yogthos** [comment]
From what I can tell it looks like navigation can only be hooked up once, so you do have to reload the page when adding new routes.
