### ISSUE TITLE
Tinkering with template for cljs > 2755

### ISSUE THREAD

**Issue by numinasthmatic** [reagent-project/reagent-template#34]
I've been tinkering with reagent-template to try to create projects which depend on the most recent facilities in clojurescript.  This is tricky, because of my very limited understanding of the whole ecosystem, and the fact that it keeps changing.

Reagent itself has been updated to accommodate these changes, but, according to this message
https://github.com/tomjakubowski/weasel/pull/44
the set of necessary changes will not be complete until the next release of clojurescript (somewhere beyond 2779), at which time weasel will also be updated.

Given my poor initial understanding, the chances I will sort this out are slim.  However, I would appreciate being able to ask questions in this issue thread about puzzles I encounter.

**Comment by yogthos** [comment]
The [Reagent Google group](https://groups.google.com/forum/#!forum/reagent-project) would be the best place for that. The issues section is meant more for bug tracking than general discussion.

**Comment by numinasthmatic** [comment]
Ok.  Are you looking at these changes yourself?

**Comment by yogthos** [comment]
For this issue it looks like the best thing to do might be to wait for the updates for both weasel and cljs. I'll keep an eye on the updates for this and make releases as they happen.
