### ISSUE TITLE
Feature request: Instructions on how to get a browser repl from within cider.

### ISSUE THREAD

**Issue by gstamp** [reagent-project/reagent-template#38]
It's not clear after running cider-jack-in how I might go about getting a browser repl from within cider.

**Comment by yogthos** [comment]
I don't use Emacs myself, so unfortunately can't help there much. If you do figure it out I'd like to update the docs though. :)

**Comment by Frozenlock** [comment]
I use [piggieback](https://github.com/cemerick/piggieback). FWIW, I'm trying stick with cljs 2371 for a while to give the chance to the different tools to adjust the new cljs changes.

**Comment by gstamp** [comment]
Thanks, if I figure it out I'll be sure to put in another PR.  At the moment I'm getting an error with my app when compiling the minified production version which I'm trying to work out.
