### ISSUE TITLE
Does not work with IE9 

### ISSUE THREAD

**Issue by vipenzo** [reagent-project/reagent-template#44]
You just see a console error saying "ClojureScript could not load :main, did you forget to specify :asset-path?"

(same installation working with chrome)

**Comment by yogthos** [comment]
I don't actually have a windows machine to troubleshoot on. If you can figure what's happening with IE I'd love a pr for this.

**Comment by vipenzo** [comment]
The first problem I see has to do with the execution order of async scripts, it's described here http://stackoverflow.com/questions/94141/javascripts-document-write-inline-script-execution-order.
Following one of the suggestions I modified app.js adding "defer" to every script:
----  app.js ----
if(typeof goog == "undefined") document.write('<script defer src="js/out/goog/base.js"></script>');
document.write('<script defer src="js/out/cljs_deps.js"></script>');
document.write('<script defer >if (typeof goog != "undefined") { goog.require("myapp.dev"); } else { console.warn("ClojureScript could not load :main, did you forget to specify :asset-path?"); };</script>');
------------------

Now it goes one step forward but complains with method isDefAndNotNull not supported by goog at line 345 of base.js. 
This is strange since the function is defined later in the same file.
I'm not able to understand it because I have no idea of how Closure is orchestrated.
Is COMPILED supposed to be false ?

**Comment by yogthos** [comment]
I'm really not sure about this one. However, have you tried running production compiled version in IE9 to see if the same problem persists. If the compiled version works, then I would simply recommend not doing development using IE9.

**Comment by vipenzo** [comment]
I did an uberjar and run it from there, but it does not work (this time with a different error: 
  SCRIPT438: object does not support isArray
  in app.js 24,289)

again I checked with chrome and it runs ok.

**Comment by yogthos** [comment]
Unfortunately, I'm really not sure what might be causing this. Typically, you'd end up with problems on IE9 when using Js features that it doesn't support, such as the console log. It might require some shims, you can see an example [here](https://github.com/yogthos/yuggoth/blob/5660bc223ee39de28996377226fea6d93ca07edf/resources/templates/app.html#L25). This might help resolve the issue.

**Comment by lvh** [comment]
As long as availability of IE is the issue, MS makes these available for free for precisely this purpose: http://dev.modern.ie/tools/vms/

They also have a thing called RemoteIE which apparently runs IE on an Azure box.

**Comment by yogthos** [comment]
I think the issue here is the effort required to debug IE9 as it provides very poor tooling. Practically speaking I simply wouldn't have the time for that.

**Comment by Whoops** [comment]
Plus your correct in that the React shim's are the fix for the `isArray` error. Perhaps they should be included in the template by default, but I'm not sure on that. I managed to write a fairly complex webapp that works fine in IE 9 without them, so I'm not sure what situations they are required in.

**Comment by yogthos** [comment]
I think the cookbook would probably be a better place for this.

**Comment by yogthos** [comment]
I'm going to close this one as IE9 has officially been deprecated, and I don't expect Reagent will support it going forward.
