### ISSUE TITLE
add sass/less profiles

### ISSUE THREAD

**Issue by yogthos** [reagent-project/reagent-template#47]

**Comment by petrvolny** [comment]
I will try to tackle this one but I am completely new to clojure/clojurescript so please have a patience with me ;)

**Comment by yogthos** [comment]
sounds great :+1:

**Comment by yogthos** [comment]
the [chestnut template](https://github.com/plexus/chestnut) might be worth look at to see how it adds less support

**Comment by lvh** [comment]
Since this is now added, and the template ostensibly supports +sass as well, should this ticket be closed?

**Comment by Atsman** [comment]
@lvh the same question from me

**Comment by yogthos** [comment]
yeah I think we can close this one
