### ISSUE TITLE
println in development must be removed in production

### ISSUE THREAD

**Issue by arsenerei** [reagent-project/reagent-template#49]
I've left comments in for debugging and production will fail since the enable-console-print! is not called in production.  Is it proper just to remove them?  I find them useful to keep sometimes between versions and I'd rather silently ignore them than have to outright remove them.

**Comment by yogthos** [comment]
Ideally, you wouldn't put comments in for production. However, you could set the `*print-fn*` to something like `(fn [& args])` that will simply ignore print statements in prod. You could do that by editing `env/prod/cljs/<app-name>/prod.cljs` and adding the following line there:

```clojure
(set! *print-fn* (fn [& -]))
```

You can take a look for some more details on what's going on with `println` in cljs [here](http://toblux.com/2014/01/08/enable-console-print-in-clojurescript/).

**Comment by yogthos** [comment]
I'll update the template to do this by default as I don't really see any harm in that.

**Comment by arsenerei** [comment]
Thanks, I appreciate it. I added it in my project and it worked out.
