### ISSUE TITLE
"No value supplied for key: weasel.repl.websocket..."

### ISSUE THREAD

**Issue by mhuebert** [reagent-project/reagent-template#50]
I've been trying to get a browser repl working using a fresh "lein new reagent ..." project.

I get the following error whenever the `(cemerick.piggieback/cljs-repl :repl-env (weasel.repl.websocket/repl-env))` line is run (manually with options in the repl, or otherwise):

```clj
Unhandled java.lang.IllegalArgumentException
   No value supplied for key:
   weasel.repl.websocket.WebsocketEnv@af47e25b
```
Reproduction:
```
$ lein new reagent test
$ cd test
$ lein figwheel
; open localhost:3449 and open a new terminal window
$ lein repl
...
test.repl=> (browser-repl)

IllegalArgumentException No value supplied for key: weasel.repl.websocket.WebsocketEnv@af47e25b  clojure.lang.PersistentHashMap.create (PersistentHashMap.java:77)
```
I don't imagine everyone is experiencing this so I am not sure how to track down the problem. Any ideas would be appreciated.

**Comment by mhuebert** [comment]
I believe this was caused by commit 8bd53240b661996afd430625393742b079fa347e, because 0.2.0 of piggieback has a new API: https://github.com/cemerick/piggieback/commit/47362bb935558db49dc906e24c5d7ba9160e4d72#diff-f31bb735cb21ecf0a8ba8ec3949a7c6aR145

I think I can make a patch for this.

**Comment by yogthos** [comment]
a pr would be great! ;)

**Comment by lvh** [comment]
This no longer seems relevant since we're using figwheel's nREPL integration?

**Comment by yogthos** [comment]
I think so :)
