### ISSUE TITLE
Unable to open up a repl with lein repl

### ISSUE THREAD

**Issue by esdee** [reagent-project/reagent-template#54]
I have created a new reagent project based on the instructions in the Readme ```lein new reagent testr``` When I type ```lein repl``` in the project directory I receive the following error

```<CompilerException java.io.FileNotFoundException: Could not locate cemerick/piggieback__init.class or cemerick/piggieback.clj on classpath: , compiling:(testr/dev.clj:1:1)>
Error loading cemerick.piggieback: Could not locate cemerick/piggieback__init.class or cemerick/piggieback.clj on classpath: 
Exception in thread "main" java.lang.RuntimeException: Unable to resolve var: cemerick.piggieback/wrap-cljs-repl in this context, compiling:(/private/var/folders/yy/s1hxr1fx0y1561k7h25lrv7c0000gn/T/form-init1127347182220128335.clj:1:2726)```

followed by a stacktrace which has 

```Caused by: java.lang.RuntimeException: Unable to resolve var: cemerick.piggieback/wrap-cljs-repl in this context``` 

near the end

**Comment by esdee** [comment]
Was able to work around this by adding the following 2 dependencies to {:profiles {:dev {:dependencies

 ```[leiningen-core "2.5.1"]```
 
```[com.cemerick/piggieback "0.2.0"]```

**Comment by yogthos** [comment]
Ah right I did a bit of a refactor and I moved those out, but now I remember why they were there. :) I just pushed out a new version with the dependencies.
