### ISSUE TITLE
PatternSyntaxException

### ISSUE THREAD

**Issue by matthewp** [reagent-project/reagent-template#57]
When running `lein do clean, figwheel` I get this error:

Caused by: java.util.regex.PatternSyntaxException: Unknown inline modifier near index 2
(?U)^[\p{Alpha}_$]

Using:

```
Leiningen 2.5.1 on Java 1.6.0_65 Java HotSpot(TM) 64-Bit Server VM
```

Does this require a certain version of Java maybe?

**Comment by matthewp** [comment]
Upgrading to Java 1.7 fixed it, should this requirement be in the readme?

**Comment by yogthos** [comment]
yeah that's a good idea, just added min JDK version
