### ISSUE TITLE
How do I run tests inside figwheel with the given setup?

### ISSUE THREAD

**Issue by thiagofm** [reagent-project/reagent-template#70]
I've been trying to discover that lately.

Running `lein cljsbuild test` takes too much time, so you don't get a fast feedback and can't TDD.

I know it's a bit of stackoverflow question, but this should also be added to the project documentation. I can add it with all the pleasure in the world if I get an answer(or discover that).

**Comment by yogthos** [comment]
The normal workflow for Clojure is to use REPL driven development instead. You shouldn't have to restart the app each time you write a function to test what it's doing. It's also possible to run tests from the REPL. I wrote a quick tutorial on using ClojureScript REPL from the editor [here](http://yogthos.net/posts/2015-06-16-Figwheel-nREPL.html).
