### ISSUE TITLE
index.html file is missing.

### ISSUE THREAD

**Issue by mswift42** [reagent-project/reagent-template#73]
With commit 1d405d661471a0f1bdf170d232087e722772e00f the index.html file in resources/templates was removed. 

How am I supposed to add static resources now (bootstrap, material design, ...) ?

**Comment by yogthos** [comment]
any public static resources should go in the `resources/public` folder. So, you might have `resources/public/css/site.css`, etc. The resources are included relative to the `public` folder in the `handler` namespace in the `home-page` template.

**Comment by mswift42** [comment]
But how do I include them? 

With an index.html file I add links to static resources in the html's head or body.

How should I load them without one?

**Comment by yogthos** [comment]
[Hiccup](https://weavejester.github.io/hiccup/) is used for HTML templating, if you look in the handler you'll see the `home-page` template that [includes CSS and Js resources](https://github.com/reagent-project/reagent-template/blob/ce4e6f215d780351f46c392013ed22afe515314f/src/leiningen/new/reagent/src/clj/reagent/handler.clj#L11) using `include-js` and `include-css` helper functions. However, any valid HTML tags are supported by Hiccup as well.

**Comment by mswift42** [comment]
Oops, failed to look into the clj folder. Thanks, got it now.

**Comment by yogthos** [comment]
no prob
