### ISSUE TITLE
Use x CSS preprocessing language

### ISSUE THREAD

**Issue by mikejholly** [reagent-project/reagent-template#77]
I noticed there is a way to get Less running but I'd like to use Stylus or SCSS.

I'd love to contribute if you can give me a starting point. 

Cheers!

**Comment by mikejholly** [comment]
Oh, BTW. Reagent is exceptional!

**Comment by yogthos** [comment]
@mikejholly sorry for the really long delay, I've missed this one :) If you'd like to try a pr then I'd take a look at [lein-sassy](https://github.com/vladh/lein-sassy), [lein-scss](https://github.com/bluegray/lein-scss), or [lein-sass](https://github.com/101loops/lein-sass). I'm not sure which one works best though. I can help out with testing the pr and any questions.
