### ISSUE TITLE
what port do i use for cider-connect? 

### ISSUE THREAD

**Issue by jdkealy** [reagent-project/reagent-template#78]
i see nrepl is included by default

**Comment by yogthos** [comment]
The nrepl is setup by figwheel, so it should be available on port 7002, I don't use emacs though so can't help with anything cider specific. :)

**Comment by Whoops** [comment]
I do use Emacs. For this template, 7002 is correct. It's set by the `:nrepl-port 7002` piece under `:figwheel` in the `project.clj`

**Comment by jdkealy** [comment]
Yes thank you. It's correct. Thanks so much. Sorry it's right there in the
source code, it says 7002

On Tue, Aug 18, 2015 at 6:47 PM, Walton Hoops <notifications@github.com>
wrote:

> I do use Emacs. For this template, 7002 is correct. It's set by the :nrepl-port
> 7002 piece under :figwheel in the project.clj
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/reagent-project/reagent-template/issues/78#issuecomment-132380330>
> .
>



-- 
Sincerely
-John-
