### ISSUE TITLE
Make the pages reloadable?

### ISSUE THREAD

**Issue by bsteuber** [reagent-project/reagent-template#86]
In the route definitions, if you replace e.g. the #'home-page by 'home-page, changes to the page components will automatically reload them when using figwheel. Would this have any drawbacks?

**Comment by yogthos** [comment]
The components should reload currently with figwheel already. Is this not the case for you?

**Comment by bsteuber** [comment]
Nope if I change a component it's not being reloaded, I thought that's
because the route definition is unchanged and due to the #' it keeps its
pointer to the old version. When removing the # it works like I expected.
Is it different on your machine?

Dmitri Sotnikov <notifications@github.com> schrieb am Do., 29. Okt. 2015
13:58:

**Comment by yogthos** [comment]
The components reload as expected when I edit the namespace and save it. How are you updating the component in your case?

Using the `#'` creates a var that should be resolved to the new component each time. The reason it's used is so that when a page is in a different namespace it still gets resolve correctly and reloads. If you keep the pointer to the old version then that gets lost during the reload.

**Comment by bsteuber** [comment]
Oh you're right - the reloading only fails when I do "lein figwheel
devcards". Is that a bug or expected behavior, meaning the devcard build
will simply only reload the devcards and nothing else?

**Comment by yogthos** [comment]
Yeah, so those are two separate builds. When you're running the devcards build you should reference the pages in the devcards namespace, e.g:


```clojure
(ns app.cards
  (:require [reagent.core :as reagent :refer [atom]]
            [reagent.session :as session]
            ;;reference the core namespace
            [app.core :as core])
  (:require-macros
   [devcards.core
    :as dc
    :refer [defcard defcard-doc defcard-rg deftest]]))

(defcard-rg first-card
  ;;render the page from the core namespace
  [core/home-page])
```

The updates in the `core/home-page` should now be reflected live in the devcard.

**Comment by bsteuber** [comment]
That makes sense, thx for your quick help!

**Comment by yogthos** [comment]
no prob, and I updated the template to add the `home-page` in the devcards as an example
