### ISSUE TITLE
Add 'cljs-only' option

### ISSUE THREAD

**Issue by px0** [reagent-project/reagent-template#90]
One of the appeals of CLJS is that it is fairly simple to throw onto an already existing architecture, for instance S3, or even to just run it as a local file. For that to work with this template, there are two things that need to be changed: 

1) The newly added *accountant* library needs to be removed again, because it requires modification to the server, which fragment-based routing does not need

2) There needs to be a leiningen target that compiles a production build of clojurescript (Something like https://github.com/px0/jiyi/blob/5e32e28512b2b071a03710787cfaee525b6ac1bb/project.clj#L101)

It would be great to get this supported!

**Comment by yogthos** [comment]
oh btw looking at this I noticed the Figwheel template might fit the bill already as it has a Reagent profile https://github.com/bhauman/figwheel-template running `lein new figwheel hello-world --reagent` will produce pretty much what I would've added I think.

**Comment by mgerlach-klick** [comment]
The 'cljsbuild min' part looks solid, but the rest of the template is very bare-bones. There is no routing at all, nor some of the other goodies that ship with this template (the env/prod setup, the additional reagent modules, etc).

**Comment by yogthos** [comment]
ah makes sense, I'll take a look at making something a bit more batteries included from it

**Comment by ducky427** [comment]
+1

**Comment by yogthos** [comment]
I ended up making a separate [template](https://github.com/reagent-project/reagent-frontend-template) for the front-end only option. Should address the issue.

**Comment by mgerlach-klick** [comment]
That is awesome! Thank you!

On Fri, Feb 12, 2016 at 9:40 AM, Dmitri Sotnikov <notifications@github.com>
wrote:

> Closed #90 <https://github.com/reagent-project/reagent-template/issues/90>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/reagent-project/reagent-template/issues/90#event-548603777>
> .
>



-- 
Maximilian Gerlach
Senior Mobile Developer

T: 416-214-4977 x2381
mgerlach@klick.com



Klick Health
www.klick.com

Klick is proud to have been recognized as one of the country’s:
• 50 Best Managed Companies
• 50 Best Employers
• 50 Fastest Growing Companies
