### ISSUE TITLE
'lein clean' doesn't remove the devcards generated JS

### ISSUE THREAD

**Issue by Frozenlock** [reagent-project/reagent-template#91]
This one bit me hard.

**Comment by yogthos** [comment]
oh oops I think I forgot to update the target paths for devcards after I switched to using target/cljsbuild path

**Comment by Frozenlock** [comment]
While this may be true, I've got this problem on an old (2-3 weeks) template.

**Comment by yogthos** [comment]
I just checked in an update, can you try with the latest and see if it works correctly. I tested cleaning and seemed to work as expected.

**Comment by Frozenlock** [comment]
Yup, works perfectly.

As always, thanks for the lightning-speed fix. :smile:

**Comment by yogthos** [comment]
no prob, I'll push it out shortly
