### ISSUE TITLE
POST request and X-CSRF token

### ISSUE THREAD

**Issue by iloginov** [reagent-project/reagent-template#92]
I got `Invalid anti-forgery token` when make POST request. Most simple way of avoiding that I found on the net is [use Selmer as templating engine](https://groups.google.com/forum/#!msg/clojurescript/bL3Jm6TY_54/qzZurs16CIcJ):

```html
<script type=javascript> 
  var csrf = "{{csrf-token}}"; 
</script> 
```

or disable `:anti-forgery` in `site-defaults` as described [here](http://masato.github.io/2015/05/17/compojure-invalid-anti-forgery-token/).

I'm wonder if there is simple way to make POST request and do not disable anti-forgery.

Thx.

**Comment by yogthos** [comment]
You do have to explicitly include the token, if you're using Hiccup then you can use `(ring.util.anti-forgery/anti-forgery-field)` in the form. It will create the necessary HTML field for validation.

**Comment by Conaws** [comment]
@yogthos can you illustrate this with an example...

What do you mean by 'the form'?
What if the post request is coming from a reagent element that isn't inside a form per-se?

**Comment by yogthos** [comment]
If you're doing an ajax post from ClojureScript, then you need to add a csrf header. You can take a look [here](https://github.com/ClojureTO/guestbook/blob/master/src/cljs/guestbook/ajax.cljs) for an example. The code there uses the [cljs-ajax](https://github.com/JulianBirch/cljs-ajax) library and creates an interceptor that will inject the header for each request. The `js/csrfToken` variable has to be generated on the page.

**Comment by uehlbran** [comment]
That example couldn't be more complicated for a beginner to understand. Can you show a non-convoluted example?
